name: Tests
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: alaviss/setup-nim@0.1.1
      with:
        version: 'devel' # The Nim nightly version branch to downloa
    - run: nimble test -y -d:ssl
